name: JIRA tickets

on:
  push
  # issues:
  #   types: [opened]

jobs:
  create_ticket_from_issue:
    name: Create JIRA ticket
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: DRV
          issuetype: Bug
          # summary: GITHUB ISSUE ${{issue.id}} ${{ issue.title }}
          summary: Summary test
          # description: ${{issue.url}} \r\n ${{issue.body}}
          description: desc test
          fields: '{"labels": ["github"], "components": ["JavaScript Driver"]}'

      - name: Set triage state
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "TRIAGE"

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"